name: SQA CI & CT Pipeline
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Server Ubuntu sudah terinstal Chrome & Chromedriver
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup PHP Environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: xdebug # Diperlukan untuk Metrik Coverage

    - name: Install PHP Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Start PHP Server in Background
      run: php -S localhost:8000 &

    - name: Start ChromeDriver in Background
      run: chromedriver --port=9515 --url-base=wd/hub &

    - name: Run All Automated Tests & Quality Metrics
      # Mengeksekusi seluruh pengujian di dalam folder tests/ (termasuk SystemTest.php)
      run: vendor/bin/phpunit tests/ --coverage-text